config/routes.rb
Rails.application.routes.draw do
  devise_for :administradors, controllers: {sessions: 'administradors/sessions'}
  devise_for :users, controllers: {sessions: 'users/sessions'}
  
  get 'order_details/new'

  get 'order_details/show'

  get 'order_details/destroy'

  get 'payment/send'

  get 'payment/receive'
  get'/posts_create',to:'posts#create'

  resources :posts do #cambiar las rutas
      resources :comments #cambiar las rutas
  end

   root 'posts#index'

    get '/diana' => 'posts#new'
    get '/martinez',to:'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
	validates_presence_of :title
	validates_length_of :body, :in => 10..400,:message =>"longitud no valida"
	has_many :comments
	belongs_to :user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    protect_from_forgery :except => [:index, :create, :new]
    before_action :set_post, only: [:show, :edit, :update, :destroy]


  # GET /posts
  # GET /posts.json
  
  def index
    if administrador_signed_in?
      authenticate_administrador!
      @posts = Post.all
      respond_to do |format|
                format.json do
                    render :json => @posts, :callback => params[:callback]
                  end
                  format.html
                end

    else
      authenticate_user!
    @posts = current_user.posts
    end
  end
     
   # GET /posts/1
  # GET /posts/1.json
  def show
    @posts = Post.all
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    if user_signed_in?
    if cannot? :new, @post
      flash[:alert]="No tiene permisos para agregar Post"
      redirect_to :action=>'index', :format=>'html'
    end
  end
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = 4

    respond_to do |format|
      if @post.save
        flash[:success]="Se guardó correctamente el Post"
        format.html { redirect_to @post}
        #format.json { render :show, status: :created, location: @post }
        format.json do
          render :json=>@post, :callback=> params[:callback]
        end
      else
        format.html { render :new }
        flash[:warning]="No se guardó correctamente el Post"
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        flash[:success]="Se actualizó correctamente el Post"
        format.html { redirect_to @post}
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        flash[:warning]="No se actualizó correctamente el Post"
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|

      flash[:errors]="Se borró correctamente el Post"
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.permit(:title, :body, :fech)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, :class=> "validate[required]" %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :fech, :class=> "validate[required]" %>
  </div>
   <div class="field">
    <%= f.label "Fecha compromiso" %><br>
    <%= f.text_area :body, :class=> "validate[required]" %>
  </div>
  <section class="row">
  <div class="small-6 columns">
    <div class="actions">
      <%= f.submit 'Aceptar',:class =>'button small success radius'%>
    </div>
  </div>
</section>
<% end %>

app/views/posts/_navigation.html.erb
<nav class="top-bar" data-topbar role="navigation">
	<ul class="title-area">
		<li class="name">
			<h1><a href="#">Post</a></h1>
		</li>
	</ul>
	<section class="top-bar-section">
		<ul class="left">
			<li class="has-dropdown not-click"><a href="#">DAC-RG-10</a>
				<ul class="dropdown">
					<li class="title back js-generated" href="#">
						<h5>
							<a href="javascript:void(0)">Back</a>
						</h5>
					</li>
					<li class="parent-link show-for-small-only">
						<a class="parent-link js-generated" href="#">DAC-RG-10</a>
					</li>
					<li>
						<label>Menu</label>
					</li>
					<%if user_signed_in? %>
					<li><%= link_to'Ver',controller:'/posts',action:'index'%></li>
					<li><%= link_to'Nuevo',controller:'/posts',action:'new'%></li>
					<%end%>
				</ul>

			</li>
			<li class="divider"></li>
		</ul>
		<ul class="right">
			
			
			<p class="navbar-text pull-right">
				<%if !user_signed_in? && !administrador_signed_in? %>
				<%= link_to"Ingresar",new_user_registration_path, :class=>'navbar-link'%>
				<%= link_to"Registrar",new_user_registration_path, :class=>'navbar-link'%>
				<%else%>
				<li><a>logged ini as <strong><%=current_user ? current_user.email : current_administrador.email %></strong>.</a></li>
				<%end%>
				  <%if user_signed_in? %>
					Logged in as <strong><%=current_user.email%></strong>.
					<%=link_to 'Edit profile',edit_user_registration_path, :class=>'nevbar-link'%> |
					<%=link_to "Logout",destroy_user_session_path,method: :delete,:class=>'navbar-link'%>
					<%end%>
				  <%if administrador_signed_in? %>
				  Logged in as <strong><%=current_administrador.email%></strong>.
					<%=link_to 'Edit profile',edit_user_registration_path, :class=>'nevbar-link'%> |
					<%=link_to "Logout",destroy_user_session_path,method: :delete,:class=>'navbar-link'%>
				  <%end%>
            
			

		</ul>
	</section>

</nav>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>email</th>
      <th>Body</th>
      <th>Creado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr class = "success">
        <td><%= post.title %></td>
        <td><%= User.find(post.user_id).email%></td>
        <%if post.body %>
        <td>
          <a href="#"data-reveal-id="post-<%=post.id%>">Ver Post</a>
        </td>
          <div id="post-<%=post.id%>" class="reveal-modal" data-reveal>
          <%=post.body %>
          <a class="close-reveal-modal">&#215;</a>
        </div>
        <%end%>
        </td>
        <td><%= post.created_at %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
<%= link_to 'New Post', new_post_path, :class => 'Disabled button small radius' %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>


<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<div id="comments">
	<%= render :partial => @post.comments.reverse %>
</div>

<%= form_for([@post,Comment.new], remote: true)do |f| %>
	<p> <%= f.label :body,"New Comment"%> <br/>
	<%= f.text_area :body %>
	<p/>

	 <section class="row">
  <div class="small-6 columns">
    <div class="actions">
      <%= f.submit 'Add Coment',:class =>'button small success radius'%>
    </div>
  </div>
</section>
<%end%>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>